# Generated by Django 4.2.4 on 2023-12-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=600)),
                ('holiday_description', models.CharField(max_length=6000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
