# Generated by Django 5.0 on 2023-12-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='holiday_description',
        ),
        migrations.AddField(
            model_name='holiday',
            name='end_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
