# Generated by Django 5.0 on 2023-12-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_rename_date_holiday_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_datetime',
            new_name='start_date',
        ),
    ]
