# Generated by Django 5.0 on 2023-12-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_rename_end_datetime_event_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='holiday_name',
            new_name='name',
        ),
    ]
