# Generated by Django 5.0 on 2024-01-16 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_rename_holiday_name_holiday_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
