# Generated by Django 5.0 on 2024-01-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_event_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.TextField(blank=True),
        ),
    ]
